Support authentication methods for blobs
buildpacks-community/kpack pull request #1616
Opened 2024-05-17 19:37 UTC by chenbh

closes #1503 and #1594 

Introduce a `.spec.source.blob.auth` field with 3 options:
- `""`: no auth performed
- `"secret"`: find all secrets with `kpack.io/blob` annotation (with same domain matching rules as git secret). And use it for basic auth username/password, oauth2 bearer token, or arbitrary `Authorization` header.
- `"helper"`: use IaaS specific IAM mechanisms (i.e. mapping IaaS service accounts/IDs/roles to k8s ServiceAccount) to retrieve an oauth2 token. This PR only implements it for GCP and Azure as those are the 2 envs I have easy access to, but the general interface and registration is simple enough for anyone to contribute.

2024-05-20 08:07 UTC, zhoufenqin commented on pkg/blob/azure_keychain.go
> +	tk, err := cred.GetToken(context.Background(), policy.TokenRequestOptions{Claims: claim})
should set Scopes thant than Claims
`policy.TokenRequestOptions{Scopes: []string{xxx}}`

2024-05-22 12:49 UTC, tomkennedy513 approved these changes

2024-05-27 08:35 UTC, yilims requested changes

2024-05-27 08:35 UTC, yilims commented on pkg/blob/file_keychain.go
> +			authHeader = append(authHeader, base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%v:%v", cred.username, cred.password))))
missing "Basic " here: 
authHeader = append(authHeader, "Basic "+base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%v:%v", cred.username, cred.password))))

2024-05-27 20:37 UTC, chenbh commented on pkg/blob/file_keychain.go
> +			authHeader = append(authHeader, base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%v:%v", cred.username, cred.password))))
Good catch!

2024-05-30 15:43 UTC, merged